//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentManagerLibrary.ModelLibrary.EntityFrameworkLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogueCriteria
    {
        public CatalogueCriteria()
        {
            this.DocumentDetails = new HashSet<DocumentDetail>();
            this.DocumentTransactions = new HashSet<DocumentTransaction>();
            this.DocumentTransactions1 = new HashSet<DocumentTransaction>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual ICollection<DocumentDetail> DocumentDetails { get; set; }
        public virtual ICollection<DocumentTransaction> DocumentTransactions { get; set; }
        public virtual ICollection<DocumentTransaction> DocumentTransactions1 { get; set; }
    }
}
